"""Catálogo de condições — categorias alinhadas aos dados reais do motor."""

from __future__ import annotations

CONDITION_CATEGORIES: list[dict] = [
    {
        "id": "mercado",
        "label": "Mercado",
        "description": "Mercado recomendado pelo motor",
        "fields": [
            {
                "id": "best_market",
                "label": "Mercado",
                "type": "market",
                "operators": ["eq", "in_list"],
            }
        ],
    },
    {
        "id": "ev",
        "label": "EV / Valor",
        "description": "Expected value da pick",
        "fields": [
            {
                "id": "best_ev_pct",
                "label": "EV %",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            }
        ],
    },
    {
        "id": "score",
        "label": "Confiança",
        "description": "Confiança global do modelo",
        "fields": [
            {
                "id": "best_score",
                "label": "Confiança total",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "should_bet",
                "label": "Dica recomendada",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "stake_level",
                "label": "Stake (1-10)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
        ],
    },
    {
        "id": "liga",
        "label": "Competição",
        "description": "Filtrar por liga ou fase",
        "fields": [
            {
                "id": "league",
                "label": "Liga",
                "type": "text",
                "operators": ["contains", "eq"],
            },
            {
                "id": "stage",
                "label": "Fase",
                "type": "text",
                "operators": ["contains"],
            },
        ],
    },
    {
        "id": "motivacao",
        "label": "Motivação",
        "description": "Motivation Gate",
        "fields": [
            {
                "id": "motivation_score",
                "label": "Score motivação",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "motivation_alignment",
                "label": "Alinhamento",
                "type": "enum",
                "operators": ["eq"],
                "options": ["strong", "neutral", "weak", "veto"],
            },
        ],
    },
    {
        "id": "transfermarkt",
        "label": "Transfermarkt",
        "description": "Inteligência de plantel",
        "fields": [
            {
                "id": "tm_alignment",
                "label": "Alinhamento TM",
                "type": "enum",
                "operators": ["eq"],
                "options": ["strong", "neutral", "weak"],
            },
            {
                "id": "tm_available",
                "label": "Dados disponíveis",
                "type": "boolean",
                "operators": ["eq"],
            },
        ],
    },
    {
        "id": "timing",
        "label": "Timing pré-jogo",
        "description": "Janela antes do kickoff",
        "modes": ["prematch"],
        "fields": [
            {
                "id": "minutes_to_kickoff",
                "label": "Minutos até ao jogo",
                "type": "number",
                "operators": ["lte", "gte"],
                "unit": "min",
            },
        ],
    },
    {
        "id": "favorito",
        "label": "Favorito",
        "description": "Favorito pré-jogo (odds ESPN/API) vs resultado live",
        "modes": ["live"],
        "fields": [
            {
                "id": "favorite_status",
                "label": "Estado do favorito",
                "type": "enum",
                "operators": ["eq", "in_list"],
                "options": ["winning", "drawing", "losing", "unknown"],
            },
            {
                "id": "favorite_losing_or_drawing",
                "label": "Favorito a perder ou empatar",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "favorite_side",
                "label": "Lado favorito",
                "type": "enum",
                "operators": ["eq"],
                "options": ["home", "away", "none"],
            },
            {
                "id": "favorite_goal_diff",
                "label": "Diferença de golos (favorito)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "favorite_winning",
                "label": "Favorito a ganhar",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "home_is_favorite",
                "label": "Casa é favorita",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "away_is_favorite",
                "label": "Fora é favorita",
                "type": "boolean",
                "operators": ["eq"],
            },
        ],
    },
    {
        "id": "cantos",
        "label": "Cantos",
        "description": "Cantos ao vivo (API-Football ou ESPN)",
        "modes": ["live"],
        "fields": [
            {
                "id": "total_corners",
                "label": "Cantos (total)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "home_corners",
                "label": "Cantos casa",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "away_corners",
                "label": "Cantos fora",
                "type": "number",
                "operators": ["gte", "lte"],
            },
        ],
    },
    {
        "id": "live",
        "label": "Ao vivo",
        "description": "Estado do jogo in-play",
        "modes": ["live"],
        "fields": [
            {
                "id": "minute",
                "label": "Minuto",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "match_status",
                "label": "Fase do jogo",
                "type": "enum",
                "operators": ["eq", "in_list"],
                "options": ["1H", "HT", "2H", "ET", "LIVE"],
            },
            {
                "id": "is_halftime",
                "label": "Intervalo (HT)",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "is_first_half",
                "label": "1.º tempo",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "is_second_half",
                "label": "2.º tempo",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "remaining_minutes",
                "label": "Minutos restantes",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "min",
            },
            {
                "id": "total_goals",
                "label": "Golos totais",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "home_score",
                "label": "Golos casa",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "away_score",
                "label": "Golos fora",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "goal_diff",
                "label": "Diferença (casa − fora)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "first_half_goals",
                "label": "Golos no 1.º tempo (live)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "ht_total_goals",
                "label": "Golos ao intervalo",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "ht_home_score",
                "label": "Golos casa ao intervalo",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "ht_away_score",
                "label": "Golos fora ao intervalo",
                "type": "number",
                "operators": ["gte", "lte"],
            },
        ],
    },
    {
        "id": "xg_live",
        "label": "Performance xG",
        "description": "Expected goals ao vivo (API ou estimativa)",
        "modes": ["live"],
        "fields": [
            {
                "id": "home_xg",
                "label": "xG casa",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "away_xg",
                "label": "xG fora",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "total_xg",
                "label": "xG total",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "xg_diff",
                "label": "Δ xG (casa − fora)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "home_possession_pct",
                "label": "Posse casa %",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
            {
                "id": "away_possession_pct",
                "label": "Posse fora %",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
        ],
    },
    {
        "id": "remates",
        "label": "Remates",
        "description": "Remates ao vivo (ESPN ou API-Football)",
        "modes": ["live"],
        "fields": [
            {
                "id": "total_shots",
                "label": "Remates (total)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "total_shots_on",
                "label": "Remates à baliza (total)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "home_shots_on",
                "label": "Remates à baliza casa",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "away_shots_on",
                "label": "Remates à baliza fora",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "home_shots_total",
                "label": "Remates casa",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "away_shots_total",
                "label": "Remates fora",
                "type": "number",
                "operators": ["gte", "lte"],
            },
        ],
    },
    {
        "id": "faltas",
        "label": "Faltas",
        "description": "Faltas cometidas ao vivo",
        "modes": ["live"],
        "fields": [
            {
                "id": "total_fouls",
                "label": "Faltas (total)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "home_fouls",
                "label": "Faltas casa",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "away_fouls",
                "label": "Faltas fora",
                "type": "number",
                "operators": ["gte", "lte"],
            },
        ],
    },
    {
        "id": "passes",
        "label": "Passes",
        "description": "Precisão de passe ao vivo",
        "modes": ["live"],
        "fields": [
            {
                "id": "home_passes_pct",
                "label": "Passe casa %",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
            {
                "id": "away_passes_pct",
                "label": "Passe fora %",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
        ],
    },
    {
        "id": "defesa",
        "label": "Defesa",
        "description": "Defesas do guarda-redes ao vivo",
        "modes": ["live"],
        "fields": [
            {
                "id": "total_saves",
                "label": "Defesas (total)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "home_saves",
                "label": "Defesas casa",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "away_saves",
                "label": "Defesas fora",
                "type": "number",
                "operators": ["gte", "lte"],
            },
        ],
    },
    {
        "id": "cartoes",
        "label": "Cartões",
        "description": "Amarelos e vermelhos ao vivo",
        "modes": ["live"],
        "fields": [
            {
                "id": "total_yellow_cards",
                "label": "Amarelos (total)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "total_red_cards",
                "label": "Vermelhos (total)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "total_cards",
                "label": "Cartões (total)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "home_yellow_cards",
                "label": "Amarelos casa",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "away_yellow_cards",
                "label": "Amarelos fora",
                "type": "number",
                "operators": ["gte", "lte"],
            },
        ],
    },
    {
        "id": "pattern_ia",
        "label": "IA — Padrão histórico",
        "description": "Compara ritmo live com médias históricas da equipa nesta situação",
        "modes": ["live"],
        "fields": [
            {
                "id": "pattern_has_profile",
                "label": "Perfil histórico disponível",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "pattern_alert",
                "label": "Alerta de discrepância",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "pattern_discrepancy_score",
                "label": "Score discrepância",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
            {
                "id": "pattern_discrepancy_trend",
                "label": "Tendência discrepância",
                "type": "number",
                "operators": ["gte", "lte", "eq"],
            },
            {
                "id": "pattern_corners_gap_pct",
                "label": "Δ cantos vs esperado",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
            {
                "id": "pattern_goals_gap_pct",
                "label": "Δ golos vs esperado",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
            {
                "id": "pattern_cards_gap_pct",
                "label": "Δ cartões vs esperado",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
            {
                "id": "pattern_situation",
                "label": "Situação detectada",
                "type": "enum",
                "operators": ["eq", "in_list"],
                "options": [
                    "fav_losing_post_ht",
                    "fav_losing_ht",
                    "fav_losing",
                    "fav_drawing",
                    "fav_winning",
                    "neutral",
                ],
            },
            {
                "id": "pattern_source",
                "label": "Fonte do perfil",
                "type": "enum",
                "operators": ["eq"],
                "options": ["situation", "season"],
            },
            {
                "id": "pattern_window",
                "label": "Janela de minutos",
                "type": "enum",
                "operators": ["eq", "in_list"],
                "options": [
                    "first_half",
                    "post_ht_0_15",
                    "post_ht_16_30",
                    "post_ht_31_45",
                ],
            },
            {
                "id": "pattern_situation_sample",
                "label": "Jogos na amostra condicional",
                "type": "number",
                "operators": ["gte", "lte"],
            },
        ],
    },
    {
        "id": "epoca",
        "label": "Época / Competição",
        "description": "Progresso da época — cenários underdog só entre 25% e 85%",
        "modes": ["prematch"],
        "fields": [
            {
                "id": "competition_progress_pct",
                "label": "Progresso época %",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
            {
                "id": "underdog_progress_ok",
                "label": "Janela underdog OK (25–85%)",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "underdog_progress_pct",
                "label": "Progresso (underdog)",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
        ],
    },
    {
        "id": "underdog",
        "label": "Underdog vs tabela",
        "description": "«Com raça» marca vs melhor classificado; «galinha» o oposto",
        "modes": ["prematch"],
        "fields": [
            {
                "id": "underdog_scenario",
                "label": "Cenário underdog",
                "type": "enum",
                "operators": ["eq", "in_list"],
                "options": [
                    "raca",
                    "galinha",
                    "raca_trend",
                    "galinha_trend",
                    "neutral",
                    "insufficient",
                    "none",
                ],
            },
            {
                "id": "underdog_significant",
                "label": "Diferença estatisticamente significativa",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "underdog_favorite_hunt",
                "label": "Caça favoritos",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "underdog_scoring_alert",
                "label": "Alerta de golos",
                "type": "enum",
                "operators": ["eq"],
                "options": [
                    "marca com facilidade vs favorito",
                    "dificuldade em marcar vs favorito",
                    "neutro",
                ],
            },
            {
                "id": "underdog_rate_vs_strong_pct",
                "label": "% a marcar vs melhor classificado",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
            {
                "id": "underdog_rate_vs_weak_pct",
                "label": "% a marcar vs pior classificado",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
            {
                "id": "underdog_table_gap",
                "label": "Distância na tabela (posições)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "underdog_z_score",
                "label": "Z-score (fortes vs fracos)",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "underdog_p_value",
                "label": "p-value (duas proporções)",
                "type": "number",
                "operators": ["lte", "gte"],
            },
            {
                "id": "underdog_games_vs_strong",
                "label": "Jogos vs melhor classificado",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "underdog_games_vs_weak",
                "label": "Jogos vs pior classificado",
                "type": "number",
                "operators": ["gte", "lte"],
            },
        ],
    },
    {
        "id": "underdog_ia",
        "label": "IA — Underdog",
        "description": "Alerta IA: marcar fácil (raça) ou difícil (galinha) com significância",
        "modes": ["prematch"],
        "fields": [
            {
                "id": "underdog_ia_active",
                "label": "Análise IA activa",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "underdog_ia_alert",
                "label": "Alerta IA",
                "type": "enum",
                "operators": ["eq", "in_list"],
                "options": ["easy_score", "hard_score", "blocked_progress"],
            },
            {
                "id": "underdog_ia_play_allowed",
                "label": "Jogada IA permitida",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "underdog_ia_favorite_hunt",
                "label": "IA — caça favoritos",
                "type": "boolean",
                "operators": ["eq"],
            },
        ],
    },
    {
        "id": "scenario_ia",
        "label": "IA — Cenários comunidade",
        "description": "Narrativas EV de comunidades vs o que acontece em campo (gate de apatia)",
        "modes": ["live"],
        "fields": [
            {
                "id": "scenario_active",
                "label": "Cenário activo",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "scenario_apathetic",
                "label": "Equipa apática",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "scenario_reaction_confirmed",
                "label": "Reação confirmada",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "scenario_reaction_score",
                "label": "Score de reação",
                "type": "number",
                "operators": ["gte", "lte"],
            },
            {
                "id": "scenario_play_allowed",
                "label": "Jogada EV permitida",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "scenario_ev_positive",
                "label": "EV+ no mercado",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "scenario_ev_aligned",
                "label": "Mercado alinhado ao cenário",
                "type": "boolean",
                "operators": ["eq"],
            },
            {
                "id": "scenario_field_gap",
                "label": "Δ campo vs narrativa",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "%",
            },
            {
                "id": "scenario_id",
                "label": "ID cenário",
                "type": "enum",
                "operators": ["eq", "in_list"],
                "options": [
                    "fav_push_post_ht",
                    "fav_draw_opens",
                    "xg_dominant_loser",
                    "late_desperation",
                    "physical_game_cards",
                ],
            },
        ],
    },
    {
        "id": "clima",
        "label": "Clima",
        "description": "Condições meteorológicas",
        "fields": [
            {
                "id": "temperature_c",
                "label": "Temperatura",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "°C",
            },
            {
                "id": "precipitation_mm",
                "label": "Chuva",
                "type": "number",
                "operators": ["gte", "lte"],
                "unit": "mm",
            },
        ],
    },
]

MARKET_OPTIONS = [
    "Vitória Casa",
    "Empate",
    "Vitória Fora",
    "Vitória Favorito",
    "Dupla Hipótese Favorito",
    "Over 1.5",
    "Over 2.5",
    "Over 3.5",
    "Under 1.5",
    "Under 2.5",
    "Under 3.5",
    "Over 0.5 HT",
    "Over 1 HT",
    "Over 1.5 HT",
    "BTTS Sim",
    "BTTS Não",
    "Dupla Hipótese 1X",
    "Dupla Hipótese X2",
    "Dupla Hipótese 12",
    "DNB Casa",
    "DNB Fora",
    "Handicap Casa",
    "Handicap Fora",
    "Golos Casa Over",
    "Golos Fora Over",
    "Cantos Over",
    "Cantos Under",
    "2.ª Parte — Casa",
    "2.ª Parte — Empate",
    "2.ª Parte — Fora",
]

BOT_TEMPLATES: list[dict] = [
    {
        "id": "prematch_over",
        "name": "Over 2.5 pré-jogo",
        "description": "Jogos abertos com EV positivo",
        "mode": "prematch",
        "markets": ["Over 2.5"],
        "min_score": 0.58,
        "min_ev_pct": 5,
        "minutes_before": 120,
        "conditions": [
            {"category": "score", "field": "should_bet", "operator": "eq", "value": True, "label": "Dica recomendada"},
        ],
    },
    {
        "id": "prematch_over15",
        "name": "Over 1.5 FT pré-jogo",
        "description": "Jogos com pelo menos 2 golos esperados — mercado Over 1.5",
        "mode": "prematch",
        "markets": ["Over 1.5", "Over 2.5"],
        "min_score": 0.56,
        "min_ev_pct": 4,
        "minutes_before": 180,
        "conditions": [
            {"category": "ev", "field": "best_ev_pct", "operator": "gte", "value": 4, "label": "EV ≥ 4%"},
        ],
    },
    {
        "id": "prematch_favorite_win",
        "name": "Vence favorito pré-jogo",
        "description": "Pick no lado favorito (casa ou fora conforme odds)",
        "mode": "prematch",
        "markets": ["Vitória Favorito", "Vitória Casa", "Vitória Fora"],
        "min_ev_pct": 3,
        "min_score": 0.55,
        "conditions": [
            {"category": "score", "field": "should_bet", "operator": "eq", "value": True, "label": "Dica recomendada"},
        ],
    },
    {
        "id": "prematch_favorite_dc",
        "name": "Vence ou empata favorito",
        "description": "Dupla hipótese no lado favorito (1X ou X2)",
        "mode": "prematch",
        "markets": ["Dupla Hipótese Favorito", "Dupla Hipótese 1X", "Dupla Hipótese X2"],
        "min_ev_pct": 2,
        "conditions": [],
    },
    {
        "id": "prematch_btts",
        "name": "BTTS pré-jogo",
        "description": "Ambas marcam com motivação forte",
        "mode": "prematch",
        "markets": ["BTTS Sim"],
        "min_ev_pct": 4,
        "conditions": [
            {"category": "motivacao", "field": "motivation_score", "operator": "gte", "value": 2, "label": "Motivação ≥ 2"},
        ],
    },
    {
        "id": "prematch_underdog_raca",
        "name": "Underdog com raça",
        "description": "Underdog marca com frequência contra melhor classificado — época 25–85%, diferença significativa",
        "mode": "prematch",
        "markets": ["BTTS Sim", "Over 1.5", "Golos Fora Over", "Golos Casa Over", "Dupla Hipótese X2", "Dupla Hipótese 1X"],
        "min_ev_pct": 3,
        "minutes_before": 180,
        "conditions": [
            {"category": "epoca", "field": "underdog_progress_ok", "operator": "eq", "value": True, "label": "Época 25–85%"},
            {"category": "underdog", "field": "underdog_scenario", "operator": "eq", "value": "raca", "label": "Perfil com raça"},
            {"category": "underdog", "field": "underdog_significant", "operator": "eq", "value": True, "label": "Significativo (p<0.05)"},
        ],
    },
    {
        "id": "prematch_underdog_galinha",
        "name": "Underdog galinha",
        "description": "Underdog raramente marca contra melhor classificado — época 25–85%, diferença significativa",
        "mode": "prematch",
        "markets": ["BTTS Não", "Under 2.5", "Under 1.5", "Vitória Casa", "Vitória Fora"],
        "min_ev_pct": 3,
        "minutes_before": 180,
        "conditions": [
            {"category": "epoca", "field": "underdog_progress_ok", "operator": "eq", "value": True, "label": "Época 25–85%"},
            {"category": "underdog", "field": "underdog_scenario", "operator": "eq", "value": "galinha", "label": "Perfil galinha"},
            {"category": "underdog", "field": "underdog_significant", "operator": "eq", "value": True, "label": "Significativo (p<0.05)"},
        ],
    },
    {
        "id": "prematch_underdog_favorite_hunt",
        "name": "Caça favoritos (underdog raça)",
        "description": "Underdog com raça significativo vs adversário do topo da tabela — época 25–85%",
        "mode": "prematch",
        "markets": ["BTTS Sim", "Over 1.5", "Golos Fora Over", "Golos Casa Over", "Dupla Hipótese X2", "Dupla Hipótese 1X"],
        "min_ev_pct": 4,
        "minutes_before": 180,
        "notify": True,
        "conditions": [
            {"category": "epoca", "field": "underdog_progress_ok", "operator": "eq", "value": True, "label": "Época 25–85%"},
            {"category": "underdog", "field": "underdog_favorite_hunt", "operator": "eq", "value": True, "label": "Caça favoritos"},
            {"category": "underdog", "field": "underdog_significant", "operator": "eq", "value": True, "label": "Significativo (p<0.05)"},
        ],
    },
    {
        "id": "prematch_underdog_raca_ia",
        "name": "IA — Underdog marca fácil",
        "description": "Alerta IA quando o underdog tem perfil «com raça» estatisticamente significativo",
        "mode": "prematch",
        "markets": ["BTTS Sim", "Over 1.5", "Golos Fora Over", "Golos Casa Over", "Dupla Hipótese X2", "Dupla Hipótese 1X"],
        "min_ev_pct": 3,
        "minutes_before": 180,
        "notify": True,
        "conditions": [
            {"category": "epoca", "field": "underdog_progress_ok", "operator": "eq", "value": True, "label": "Época 25–85%"},
            {"category": "underdog_ia", "field": "underdog_ia_alert", "operator": "eq", "value": "easy_score", "label": "Marca fácil vs favorito"},
            {"category": "underdog_ia", "field": "underdog_ia_play_allowed", "operator": "eq", "value": True, "label": "Significância confirmada"},
        ],
    },
    {
        "id": "prematch_underdog_galinha_ia",
        "name": "IA — Underdog marca difícil",
        "description": "Alerta IA quando o underdog tem perfil «galinha» — dificuldade em marcar vs favorito",
        "mode": "prematch",
        "markets": ["BTTS Não", "Under 2.5", "Under 1.5", "Vitória Casa", "Vitória Fora"],
        "min_ev_pct": 3,
        "minutes_before": 180,
        "notify": True,
        "conditions": [
            {"category": "epoca", "field": "underdog_progress_ok", "operator": "eq", "value": True, "label": "Época 25–85%"},
            {"category": "underdog_ia", "field": "underdog_ia_alert", "operator": "eq", "value": "hard_score", "label": "Marca difícil vs favorito"},
            {"category": "underdog_ia", "field": "underdog_ia_play_allowed", "operator": "eq", "value": True, "label": "Significância confirmada"},
        ],
    },
    {
        "id": "live_value",
        "name": "Valor ao vivo",
        "description": "Oportunidades in-play após min 20",
        "mode": "live",
        "min_ev_pct": 6,
        "conditions": [
            {"category": "live", "field": "minute", "operator": "gte", "value": 20, "label": "Minuto ≥ 20"},
            {"category": "score", "field": "should_bet", "operator": "eq", "value": True, "label": "Dica recomendada"},
        ],
    },
    {
        "id": "live_xg_press",
        "name": "Pressão xG live",
        "description": "Casa a dominar xG após min 25",
        "mode": "live",
        "min_ev_pct": 5,
        "conditions": [
            {"category": "live", "field": "minute", "operator": "gte", "value": 25, "label": "Minuto ≥ 25"},
            {"category": "xg_live", "field": "xg_diff", "operator": "gte", "value": 0.4, "label": "Δ xG ≥ 0.4"},
            {"category": "xg_live", "field": "home_possession_pct", "operator": "gte", "value": 52, "label": "Posse casa ≥ 52%"},
        ],
    },
    {
        "id": "live_cards",
        "name": "Jogo intenso (cartões)",
        "description": "Muitos cartões — mercados de cartões/over",
        "mode": "live",
        "markets": ["Over 2.5"],
        "conditions": [
            {"category": "live", "field": "minute", "operator": "gte", "value": 30, "label": "Minuto ≥ 30"},
            {"category": "cartoes", "field": "total_yellow_cards", "operator": "gte", "value": 3, "label": "Amarelos ≥ 3"},
        ],
    },
    {
        "id": "live_ht_over05",
        "name": "Over 0.5 HT live",
        "description": "1.º tempo sem gol — valor em Over 0.5 HT até min 35",
        "mode": "live",
        "markets": ["Over 0.5 HT"],
        "min_ev_pct": 4,
        "conditions": [
            {"category": "live", "field": "is_first_half", "operator": "eq", "value": True, "label": "1.º tempo"},
            {"category": "live", "field": "first_half_goals", "operator": "lte", "value": 0, "label": "0 golos no 1.º tempo"},
            {"category": "live", "field": "minute", "operator": "gte", "value": 18, "label": "Minuto ≥ 18"},
            {"category": "live", "field": "minute", "operator": "lte", "value": 40, "label": "Minuto ≤ 40"},
        ],
    },
    {
        "id": "live_ht_over1",
        "name": "Over 1 HT live",
        "description": "Jogo aberto no 1.º tempo — 2+ golos ao intervalo",
        "mode": "live",
        "markets": ["Over 1 HT", "Over 1.5 HT"],
        "min_ev_pct": 5,
        "conditions": [
            {"category": "live", "field": "is_first_half", "operator": "eq", "value": True, "label": "1.º tempo"},
            {"category": "live", "field": "first_half_goals", "operator": "gte", "value": 1, "label": "≥ 1 golo no 1.º tempo"},
            {"category": "live", "field": "minute", "operator": "gte", "value": 25, "label": "Minuto ≥ 25"},
        ],
    },
    {
        "id": "live_favorite_winning",
        "name": "Favorito a ganhar live",
        "description": "Favorito pré-jogo já em vantagem — confirmação de resultado",
        "mode": "live",
        "markets": ["Vitória Favorito", "Vitória Casa", "Vitória Fora"],
        "conditions": [
            {"category": "favorito", "field": "favorite_winning", "operator": "eq", "value": True, "label": "Favorito a ganhar"},
            {"category": "live", "field": "minute", "operator": "gte", "value": 20, "label": "Minuto ≥ 20"},
        ],
    },
    {
        "id": "live_favorite_trouble",
        "name": "Favorito em apuros",
        "description": "Favorito pré-jogo a perder OU empatar (odds ESPN)",
        "mode": "live",
        "condition_groups": [
            {
                "label": "Favorito em apuros",
                "logic": "or",
                "conditions": [
                    {"category": "favorito", "field": "favorite_status", "operator": "eq", "value": "losing", "label": "Favorito a perder"},
                    {"category": "favorito", "field": "favorite_status", "operator": "eq", "value": "drawing", "label": "Favorito a empatar"},
                ],
            },
            {
                "label": "Jogo iniciado",
                "logic": "and",
                "conditions": [
                    {"category": "live", "field": "minute", "operator": "gte", "value": 15, "label": "Minuto ≥ 15"},
                ],
            },
        ],
        "groups_logic": "and",
    },
    {
        "id": "live_favorite_drawing",
        "name": "Favorito só empata",
        "description": "Favorito não ganha — útil para lay/empate",
        "mode": "live",
        "conditions": [
            {"category": "favorito", "field": "favorite_losing_or_drawing", "operator": "eq", "value": True, "label": "Favorito ≤ empate"},
            {"category": "live", "field": "minute", "operator": "gte", "value": 20, "label": "Minuto ≥ 20"},
        ],
    },
    {
        "id": "live_corners_press",
        "name": "Cantos live (ESPN/API)",
        "description": "Jogo com muitos cantos — mercado cantos/over",
        "mode": "live",
        "markets": ["Cantos Over", "Over 2.5"],
        "conditions": [
            {"category": "live", "field": "minute", "operator": "gte", "value": 25, "label": "Minuto ≥ 25"},
            {"category": "cantos", "field": "total_corners", "operator": "gte", "value": 5, "label": "Cantos ≥ 5"},
        ],
    },
    {
        "id": "live_favorite_corners",
        "name": "Favorito pressiona (cantos)",
        "description": "Favorito em apuros com volume de cantos",
        "mode": "live",
        "markets": ["Cantos Over"],
        "condition_groups": [
            {
                "label": "Favorito ≤ empate",
                "logic": "or",
                "conditions": [
                    {"category": "favorito", "field": "favorite_status", "operator": "eq", "value": "losing", "label": "A perder"},
                    {"category": "favorito", "field": "favorite_status", "operator": "eq", "value": "drawing", "label": "A empatar"},
                ],
            },
            {
                "label": "Volume de cantos",
                "logic": "and",
                "conditions": [
                    {"category": "cantos", "field": "total_corners", "operator": "gte", "value": 4, "label": "Cantos ≥ 4"},
                    {"category": "live", "field": "minute", "operator": "gte", "value": 20, "label": "Minuto ≥ 20"},
                ],
            },
        ],
        "groups_logic": "and",
    },
    {
        "id": "live_espn_shots_press",
        "name": "Pressão remates (ESPN)",
        "description": "Favorito em apuros com mais remates à baliza",
        "mode": "live",
        "markets": ["Over 2.5", "Cantos Over"],
        "condition_groups": [
            {
                "label": "Favorito ≤ empate",
                "logic": "or",
                "conditions": [
                    {"category": "favorito", "field": "favorite_status", "operator": "eq", "value": "losing", "label": "A perder"},
                    {"category": "favorito", "field": "favorite_status", "operator": "eq", "value": "drawing", "label": "A empatar"},
                ],
            },
            {
                "label": "Volume de remates",
                "logic": "and",
                "conditions": [
                    {"category": "live", "field": "minute", "operator": "gte", "value": 25, "label": "Minuto ≥ 25"},
                    {"category": "remates", "field": "total_shots_on", "operator": "gte", "value": 4, "label": "À baliza ≥ 4"},
                ],
            },
        ],
        "groups_logic": "and",
    },
    {
        "id": "live_espn_fouls",
        "name": "Jogo físico (faltas ESPN)",
        "description": "Muitas faltas — over/cartões",
        "mode": "live",
        "markets": ["Over 2.5"],
        "conditions": [
            {"category": "live", "field": "minute", "operator": "gte", "value": 30, "label": "Minuto ≥ 30"},
            {"category": "faltas", "field": "total_fouls", "operator": "gte", "value": 20, "label": "Faltas ≥ 20"},
        ],
    },
    {
        "id": "live_espn_dominance",
        "name": "Domínio posse+remates",
        "description": "Equipa visitante a dominar posse e remates (ESPN)",
        "mode": "live",
        "conditions": [
            {"category": "live", "field": "minute", "operator": "gte", "value": 30, "label": "Minuto ≥ 30"},
            {"category": "xg_live", "field": "away_possession_pct", "operator": "gte", "value": 60, "label": "Posse fora ≥ 60%"},
            {"category": "remates", "field": "away_shots_on", "operator": "gte", "value": 3, "label": "À baliza fora ≥ 3"},
        ],
    },
    {
        "id": "live_espn_xg_underdog",
        "name": "Underdog com xG (ESPN)",
        "description": "Favorito atrás mas adversário com menos xG — possível reação",
        "mode": "live",
        "condition_groups": [
            {
                "label": "Favorito em apuros",
                "logic": "or",
                "conditions": [
                    {"category": "favorito", "field": "favorite_status", "operator": "eq", "value": "losing", "label": "A perder"},
                    {"category": "favorito", "field": "favorite_status", "operator": "eq", "value": "drawing", "label": "A empatar"},
                ],
            },
            {
                "label": "xG favorito superior",
                "logic": "and",
                "conditions": [
                    {"category": "live", "field": "minute", "operator": "gte", "value": 35, "label": "Minuto ≥ 35"},
                    {"category": "xg_live", "field": "xg_diff", "operator": "gte", "value": 0.3, "label": "Δ xG ≥ 0.3"},
                ],
            },
        ],
        "groups_logic": "and",
    },
    {
        "id": "live_pattern_discrepancy",
        "name": "IA — Padrão vs live",
        "description": "Favorito em apuros abaixo do ritmo histórico (cantos, golos, cartões) — discrepância crescente",
        "mode": "live",
        "markets": ["Cantos Over", "Over 1.5", "Over 2.5"],
        "notify": True,
        "condition_groups": [
            {
                "label": "Favorito em apuros",
                "logic": "or",
                "conditions": [
                    {"category": "favorito", "field": "favorite_status", "operator": "eq", "value": "losing", "label": "A perder"},
                    {"category": "favorito", "field": "favorite_status", "operator": "eq", "value": "drawing", "label": "A empatar"},
                ],
            },
            {
                "label": "Discrepância histórica",
                "logic": "and",
                "conditions": [
                    {"category": "pattern_ia", "field": "pattern_has_profile", "operator": "eq", "value": True, "label": "Perfil disponível"},
                    {"category": "pattern_ia", "field": "pattern_discrepancy_score", "operator": "gte", "value": 50, "label": "Score ≥ 50"},
                    {"category": "pattern_ia", "field": "pattern_discrepancy_trend", "operator": "gte", "value": 0, "label": "Tendência ≥ 0"},
                    {"category": "scenario_ia", "field": "scenario_apathetic", "operator": "eq", "value": False, "label": "Sem apatia"},
                    {"category": "live", "field": "minute", "operator": "gte", "value": 30, "label": "Minuto ≥ 30"},
                ],
            },
        ],
        "groups_logic": "and",
    },
    {
        "id": "live_pattern_post_ht",
        "name": "IA — Favorito a perder no HT",
        "description": "Após intervalo com favorito atrás — ritmo abaixo do padrão nos min 46–75",
        "mode": "live",
        "markets": ["Cantos Over", "Over 1.5", "Over 2.5", "Over 0.5 HT"],
        "notify": True,
        "conditions": [
            {"category": "pattern_ia", "field": "pattern_situation", "operator": "eq", "value": "fav_losing_post_ht", "label": "Janela pós-HT"},
            {"category": "pattern_ia", "field": "pattern_has_profile", "operator": "eq", "value": True, "label": "Perfil disponível"},
            {"category": "pattern_ia", "field": "pattern_corners_gap_pct", "operator": "gte", "value": 40, "label": "Cantos abaixo do esperado"},
            {"category": "live", "field": "minute", "operator": "gte", "value": 46, "label": "Minuto ≥ 46"},
            {"category": "live", "field": "minute", "operator": "lte", "value": 75, "label": "Minuto ≤ 75"},
            {"category": "scenario_ia", "field": "scenario_apathetic", "operator": "eq", "value": True, "label": "Equipa apática — aguardar"},
        ],
    },
    {
        "id": "live_pattern_conditional_window",
        "name": "IA — Janela condicional (Fase 2)",
        "description": "Discrepância vs histórico real da equipa nesta situação e janela de minutos (HTHG/HTAG)",
        "mode": "live",
        "markets": ["Cantos Over", "Over 1.5", "Over 2.5"],
        "notify": True,
        "conditions": [
            {"category": "pattern_ia", "field": "pattern_source", "operator": "eq", "value": "situation", "label": "Perfil condicional"},
            {"category": "pattern_ia", "field": "pattern_situation_sample", "operator": "gte", "value": 3, "label": "Amostra ≥ 3 jogos"},
            {"category": "pattern_ia", "field": "pattern_discrepancy_score", "operator": "gte", "value": 45, "label": "Score ≥ 45"},
            {"category": "scenario_ia", "field": "scenario_apathetic", "operator": "eq", "value": False, "label": "Sem apatia"},
            {"category": "live", "field": "minute", "operator": "gte", "value": 46, "label": "Minuto ≥ 46"},
        ],
    },
    {
        "id": "live_scenario_ev_confirmed",
        "name": "IA — EV cenário confirmado",
        "description": "Tese de comunidade + reação em campo + EV+ — só dispara quando a equipa demonstrou que voltou ao jogo",
        "mode": "live",
        "markets": ["Cantos Over", "Over 1.5", "Over 2.5", "Vitória Favorito"],
        "notify": True,
        "conditions": [
            {"category": "scenario_ia", "field": "scenario_play_allowed", "operator": "eq", "value": True, "label": "Jogada permitida"},
            {"category": "scenario_ia", "field": "scenario_reaction_confirmed", "operator": "eq", "value": True, "label": "Reação confirmada"},
            {"category": "scenario_ia", "field": "scenario_apathetic", "operator": "eq", "value": False, "label": "Sem apatia"},
            {"category": "live", "field": "minute", "operator": "gte", "value": 30, "label": "Minuto ≥ 30"},
        ],
    },
    {
        "id": "live_scenario_apathy_warn",
        "name": "IA — Apatia (não seguir tese)",
        "description": "Alerta quando a narrativa da comunidade diz para reagir mas a equipa está apática em campo",
        "mode": "live",
        "notify": True,
        "conditions": [
            {"category": "scenario_ia", "field": "scenario_active", "operator": "eq", "value": True, "label": "Cenário activo"},
            {"category": "scenario_ia", "field": "scenario_apathetic", "operator": "eq", "value": True, "label": "Equipa apática"},
            {"category": "scenario_ia", "field": "scenario_field_gap", "operator": "gte", "value": 55, "label": "Campo muito abaixo da narrativa"},
            {"category": "favorito", "field": "favorite_losing_or_drawing", "operator": "eq", "value": True, "label": "Favorito em apuros"},
        ],
    },
]

# Intervalos típicos — mostrados na UI dos filtros e condições dos bots
FIELD_RANGES: dict[str, dict] = {
    "best_ev_pct": {"min": -5, "max": 50, "step": 0.5, "range_hint": "−5–50%"},
    "best_score": {"min": 0.5, "max": 0.9, "step": 0.01, "range_hint": "0.50–0.90"},
    "stake_level": {"min": 1, "max": 10, "step": 1, "range_hint": "1–10"},
    "motivation_score": {"min": 0, "max": 4, "step": 1, "range_hint": "0–4"},
    "minutes_to_kickoff": {"min": 0, "max": 720, "step": 5, "range_hint": "0–720 min"},
    "favorite_goal_diff": {"min": -5, "max": 5, "step": 1, "range_hint": "−5–+5"},
    "minute": {"min": 0, "max": 120, "step": 1, "range_hint": "0–120"},
    "remaining_minutes": {"min": 0, "max": 90, "step": 1, "range_hint": "0–90 min"},
    "total_goals": {"min": 0, "max": 15, "step": 1, "range_hint": "0–15"},
    "home_score": {"min": 0, "max": 15, "step": 1, "range_hint": "0–15"},
    "away_score": {"min": 0, "max": 15, "step": 1, "range_hint": "0–15"},
    "goal_diff": {"min": -10, "max": 10, "step": 1, "range_hint": "−10–+10"},
    "first_half_goals": {"min": 0, "max": 8, "step": 1, "range_hint": "0–8"},
    "ht_total_goals": {"min": 0, "max": 8, "step": 1, "range_hint": "0–8"},
    "ht_home_score": {"min": 0, "max": 8, "step": 1, "range_hint": "0–8"},
    "ht_away_score": {"min": 0, "max": 8, "step": 1, "range_hint": "0–8"},
    "home_xg": {"min": 0, "max": 6, "step": 0.1, "range_hint": "0–6"},
    "away_xg": {"min": 0, "max": 6, "step": 0.1, "range_hint": "0–6"},
    "total_xg": {"min": 0, "max": 10, "step": 0.1, "range_hint": "0–10"},
    "xg_diff": {"min": -5, "max": 5, "step": 0.1, "range_hint": "−5–+5"},
    "home_possession_pct": {"min": 0, "max": 100, "step": 1, "range_hint": "0–100%"},
    "away_possession_pct": {"min": 0, "max": 100, "step": 1, "range_hint": "0–100%"},
    "total_corners": {"min": 0, "max": 30, "step": 1, "range_hint": "0–30"},
    "home_corners": {"min": 0, "max": 20, "step": 1, "range_hint": "0–20"},
    "away_corners": {"min": 0, "max": 20, "step": 1, "range_hint": "0–20"},
    "total_shots": {"min": 0, "max": 40, "step": 1, "range_hint": "0–40"},
    "total_shots_on": {"min": 0, "max": 20, "step": 1, "range_hint": "0–20"},
    "home_shots_on": {"min": 0, "max": 15, "step": 1, "range_hint": "0–15"},
    "away_shots_on": {"min": 0, "max": 15, "step": 1, "range_hint": "0–15"},
    "home_shots_total": {"min": 0, "max": 30, "step": 1, "range_hint": "0–30"},
    "away_shots_total": {"min": 0, "max": 30, "step": 1, "range_hint": "0–30"},
    "total_fouls": {"min": 0, "max": 40, "step": 1, "range_hint": "0–40"},
    "home_fouls": {"min": 0, "max": 25, "step": 1, "range_hint": "0–25"},
    "away_fouls": {"min": 0, "max": 25, "step": 1, "range_hint": "0–25"},
    "home_passes_pct": {"min": 0, "max": 100, "step": 1, "range_hint": "0–100%"},
    "away_passes_pct": {"min": 0, "max": 100, "step": 1, "range_hint": "0–100%"},
    "total_saves": {"min": 0, "max": 20, "step": 1, "range_hint": "0–20"},
    "home_saves": {"min": 0, "max": 15, "step": 1, "range_hint": "0–15"},
    "away_saves": {"min": 0, "max": 15, "step": 1, "range_hint": "0–15"},
    "total_yellow_cards": {"min": 0, "max": 12, "step": 1, "range_hint": "0–12"},
    "total_red_cards": {"min": 0, "max": 3, "step": 1, "range_hint": "0–3"},
    "total_cards": {"min": 0, "max": 15, "step": 1, "range_hint": "0–15"},
    "pattern_discrepancy_score": {"min": 0, "max": 100, "step": 5, "range_hint": "0–100"},
    "pattern_discrepancy_trend": {"min": -1, "max": 1, "step": 1, "range_hint": "−1–+1"},
    "pattern_corners_gap_pct": {"min": 0, "max": 100, "step": 5, "range_hint": "0–100%"},
    "pattern_goals_gap_pct": {"min": 0, "max": 100, "step": 5, "range_hint": "0–100%"},
    "pattern_cards_gap_pct": {"min": 0, "max": 100, "step": 5, "range_hint": "0–100%"},
    "pattern_situation_sample": {"min": 0, "max": 50, "step": 1, "range_hint": "0–50 jogos"},
    "scenario_reaction_score": {"min": 0, "max": 100, "step": 5, "range_hint": "0–100"},
    "scenario_field_gap": {"min": 0, "max": 100, "step": 5, "range_hint": "0–100%"},
    "competition_progress_pct": {"min": 0, "max": 100, "step": 1, "range_hint": "0–100%"},
    "underdog_progress_pct": {"min": 0, "max": 100, "step": 1, "range_hint": "25–85%"},
    "underdog_rate_vs_strong_pct": {"min": 0, "max": 100, "step": 1, "range_hint": "0–100%"},
    "underdog_rate_vs_weak_pct": {"min": 0, "max": 100, "step": 1, "range_hint": "0–100%"},
    "underdog_table_gap": {"min": 1, "max": 20, "step": 1, "range_hint": "1–20"},
    "underdog_z_score": {"min": -5, "max": 5, "step": 0.1, "range_hint": "−5–+5"},
    "underdog_p_value": {"min": 0, "max": 1, "step": 0.01, "range_hint": "0–1"},
    "underdog_games_vs_strong": {"min": 0, "max": 40, "step": 1, "range_hint": "0–40"},
    "underdog_games_vs_weak": {"min": 0, "max": 40, "step": 1, "range_hint": "0–40"},
    "home_yellow_cards": {"min": 0, "max": 8, "step": 1, "range_hint": "0–8"},
    "away_yellow_cards": {"min": 0, "max": 8, "step": 1, "range_hint": "0–8"},
    "temperature_c": {"min": -15, "max": 45, "step": 1, "range_hint": "−15–45°C"},
    "precipitation_mm": {"min": 0, "max": 50, "step": 0.1, "range_hint": "0–50 mm"},
}

BOT_WIZARD_FILTERS: list[dict] = [
    {
        "id": "min_score",
        "draft_key": "min_score",
        "input_id": "bot-f-min-score",
        "label": "Confiança mínima",
        "placeholder": "0.55",
        "modes": ["prematch", "live"],
        **FIELD_RANGES["best_score"],
    },
    {
        "id": "min_ev_pct",
        "draft_key": "min_ev_pct",
        "input_id": "bot-f-min-ev",
        "label": "EV mín. %",
        "placeholder": "5",
        "modes": ["prematch", "live"],
        **FIELD_RANGES["best_ev_pct"],
    },
    {
        "id": "minutes_before",
        "draft_key": "minutes_before",
        "input_id": "bot-f-mins-before",
        "label": "Máx. min antes kickoff",
        "placeholder": "120",
        "modes": ["prematch"],
        "min": 5,
        "max": 720,
        "step": 5,
        "range_hint": "5–720 min",
    },
    {
        "id": "max_stake_level",
        "draft_key": "max_stake_level",
        "input_id": "bot-f-max-stake",
        "label": "Stake máx.",
        "placeholder": "10",
        "modes": ["prematch", "live"],
        **FIELD_RANGES["stake_level"],
    },
]


def _enrich_field(field: dict) -> dict:
    out = dict(field)
    extra = FIELD_RANGES.get(field.get("id", ""))
    if extra:
        out.update(extra)
    return out


def _enrich_categories(categories: list[dict]) -> list[dict]:
    out = []
    for cat in categories:
        enriched = dict(cat)
        enriched["fields"] = [_enrich_field(f) for f in cat.get("fields") or []]
        out.append(enriched)
    return out


def catalog_payload() -> dict:
    return {
        "categories": _enrich_categories(CONDITION_CATEGORIES),
        "markets": MARKET_OPTIONS,
        "templates": BOT_TEMPLATES,
        "wizard_filters": BOT_WIZARD_FILTERS,
        "operators": {
            "eq": "é",
            "neq": "não é",
            "gte": "≥",
            "lte": "≤",
            "contains": "contém",
            "in_list": "está em",
        },
        "logic_options": {
            "conditions_logic": {
                "and": "Todas (AND)",
                "or": "Qualquer (OR)",
            },
            "groups_logic": {
                "and": "Todos os grupos (AND)",
                "or": "Qualquer grupo (OR)",
            },
            "group_logic": {
                "and": "Todas no grupo (AND)",
                "or": "Qualquer no grupo (OR)",
            },
        },
    }